### ISSUE TITLE
Address deprection warning in calculate.py

### ISSUE THREAD

**Issue by christofs** [cligs/pyzeta#13]
warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/usr/local/lib/python3.5/dist-packages/sklearn/preprocessing/data.py:321: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.

**Comment by azehe** [comment]
Should be fixed in branch dev (https://github.com/cligs/pyzeta/tree/dev).
Since 0.17, sklearn expects two-dimensional arrays as input to fit_transform() etc. Converting [1,2,3] to [[1,2,3]] removes the warning. Later, the results have to be flattened again, in order to enable merging them into a DataFrame.

**Comment by christofs** [comment]
Fixed by Albin.
